services:
    init-app:
        build: .
        restart: on-failure
        ports:
            - 3000:3000
        depends_on:
            mysql_self:
                condition: service_healthy
        networks:
            - backend
        environment:
            DB_TYPE: 'mysql'
            DB_HOST: 'mysql_self'
            DB_PORT: 3306
            DB_USERNAME: 'mcdonalds'
            DB_PASSWORD: 'MfDZk"rTtn[f>j%'
            DB_DATABASE: 'self-service'
            PORT: 3000
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
        command: sh -c "npm run migration:up"
    app:
        build: .
        restart: on-failure
        ports:
            - 3000:3000
        depends_on:
            mysql_self:
                condition: service_healthy
        networks:
            - backend
        environment:
            DB_TYPE: 'mysql'
            DB_HOST: 'mysql_self'
            DB_PORT: 3306
            DB_USERNAME: 'mcdonalds'
            DB_PASSWORD: 'MfDZk"rTtn[f>j%'
            DB_DATABASE: 'self-service'
            PORT: 3000
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1GB
        command: sh -c "npm start && npm run migration:up"
    mysql_self:
        image: mysql:5.7
        restart: on-failure
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootUser#1234
            MYSQL_DATABASE: self-service
            MYSQL_USER: mcdonalds
            MYSQL_PASSWORD: MfDZk"rTtn[f>j%
        networks:
            - backend
        volumes:
            - /var/lib/mysql-self
        healthcheck:
            test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    backend:
        driver: bridge
