name: "Setup, test and build"

on:
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read
  # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Checkout repository'
        run: npm ci
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
  
  vulnerabilities:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Run Security Audit'
        run: npm audit

  tests:
    needs: [setup, vulnerabilities]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Run Unit Tests'
        run: npm run test:unit
      - name: 'Run Integration Tests'
        run: npm run test:integration

  build:
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: 'Use Node.js ${{ matrix.node-version }}'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:unit
    - run: npm run test:integration