name: 'Setup and build'

on:
  pull_request:
    branches: [ "main", "development" ]

permissions:
    contents: read
    pull-requests: write

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 'Checkout repository'
              run: npm ci
            - name: 'Dependency Review'
              uses: actions/dependency-review-action@v4
              with:
                  comment-summary-in-pr: always

    vulnerabilities:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 'Checkout repository'
              run: npm ci
            - name: 'Run Security Audit'
              run: npm audit

    build:
        runs-on: ubuntu-latest
        needs: setup
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        steps:
            - uses: actions/checkout@v4
            - name: 'Use Node.js ${{ matrix.node-version }}'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run test:unit
            - run: npm run test:integration
